<?php
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;


class MunicipioSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        
        DB::table('municipio')->insert([ 'id_entidad'=> '1', 'nombre' => 'Alto Orinoco',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '1', 'nombre' => 'Atabapo',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '1', 'nombre' => 'Atures',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '1', 'nombre' => 'Autana',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '1', 'nombre' => 'Manapiare',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '1', 'nombre' => 'Maroa',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '1', 'nombre' => 'Río Negro',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '2', 'nombre' => 'Anaco',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '2', 'nombre' => 'Aragua',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '2', 'nombre' => 'Manuel Ezequiel Bruzual',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '2', 'nombre' => 'Diego Bautista Urbaneja',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '2', 'nombre' => 'Fernando Peñalver',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '2', 'nombre' => 'Francisco Del Carmen Carvajal',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '2', 'nombre' => 'General Sir Arthur McGregor',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '2', 'nombre' => 'Guanta',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '2', 'nombre' => 'Independencia',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '2', 'nombre' => 'José Gregorio Monagas',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '2', 'nombre' => 'Juan Antonio Sotillo',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '2', 'nombre' => 'Juan Manuel Cajigal',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '2', 'nombre' => 'Libertad',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '2', 'nombre' => 'Francisco de Miranda',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '2', 'nombre' => 'Pedro María Freites',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '2', 'nombre' => 'Píritu',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '2', 'nombre' => 'San José de Guanipa',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '2', 'nombre' => 'San Juan de Capistrano',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '2', 'nombre' => 'Santa Ana',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '2', 'nombre' => 'Simón Bolívar',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '2', 'nombre' => 'Simón Rodríguez',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '3', 'nombre' => 'Achaguas',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '3', 'nombre' => 'Biruaca',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '3', 'nombre' => 'Muñóz',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '3', 'nombre' => 'Páez',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '3', 'nombre' => 'Pedro Camejo',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '3', 'nombre' => 'Rómulo Gallegos',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '3', 'nombre' => 'San Fernando',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '4', 'nombre' => 'Atanasio Girardot',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '4', 'nombre' => 'Bolívar',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '4', 'nombre' => 'Camatagua',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '4', 'nombre' => 'Francisco Linares Alcántara',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '4', 'nombre' => 'José Ángel Lamas',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '4', 'nombre' => 'José Félix Ribas',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '4', 'nombre' => 'José Rafael Revenga',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '4', 'nombre' => 'Libertador',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '4', 'nombre' => 'Mario Briceño Iragorry',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '4', 'nombre' => 'Ocumare de la Costa de Oro',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '4', 'nombre' => 'San Casimiro',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '4', 'nombre' => 'San Sebastián',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '4', 'nombre' => 'Santiago Mariño',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '4', 'nombre' => 'Santos Michelena',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '4', 'nombre' => 'Sucre',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '4', 'nombre' => 'Tovar',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '4', 'nombre' => 'Urdaneta',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '4', 'nombre' => 'Zamora',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '5', 'nombre' => 'Alberto Arvelo Torrealba',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '5', 'nombre' => 'Andrés Eloy Blanco',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '5', 'nombre' => 'Antonio José de Sucre',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '5', 'nombre' => 'Arismendi',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '5', 'nombre' => 'Barinas',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '5', 'nombre' => 'Bolívar',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '5', 'nombre' => 'Cruz Paredes',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '5', 'nombre' => 'Ezequiel Zamora',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '5', 'nombre' => 'Obispos',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '5', 'nombre' => 'Pedraza',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '5', 'nombre' => 'Rojas',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '5', 'nombre' => 'Sosa',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '6', 'nombre' => 'Caroní',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '6', 'nombre' => 'Cedeño',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '6', 'nombre' => 'El Callao',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '6', 'nombre' => 'Gran Sabana',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '6', 'nombre' => 'Heres',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '6', 'nombre' => 'Piar',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '6', 'nombre' => 'Angostura',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '6', 'nombre' => 'Roscio',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '6', 'nombre' => 'Sifontes',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '6', 'nombre' => 'Sucre',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '6', 'nombre' => 'Padre Pedro Chien',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '7', 'nombre' => 'Bejuma',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '7', 'nombre' => 'Carlos Arvelo',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '7', 'nombre' => 'Diego Ibarra',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '7', 'nombre' => 'Guacara',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '7', 'nombre' => 'Juan José Mora',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '7', 'nombre' => 'Libertador',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '7', 'nombre' => 'Los Guayos',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '7', 'nombre' => 'Miranda',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '7', 'nombre' => 'Montalbán',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '7', 'nombre' => 'Naguanagua',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '7', 'nombre' => 'Puerto Cabello',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '7', 'nombre' => 'San Diego',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '7', 'nombre' => 'San Joaquín',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '7', 'nombre' => 'Valencia',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '8', 'nombre' => 'Anzoátegui',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '8', 'nombre' => 'Tinaquillo',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '8', 'nombre' => 'Girardot',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '8', 'nombre' => 'Lima Blanco',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '8', 'nombre' => 'Pao de San Juan Bautista',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '8', 'nombre' => 'Ricaurte',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '8', 'nombre' => 'Rómulo Gallegos',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '8', 'nombre' => 'San Carlos',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '8', 'nombre' => 'Tinaco',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '9', 'nombre' => 'Antonio Díaz',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '9', 'nombre' => 'Casacoima',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '9', 'nombre' => 'Pedernales',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '9', 'nombre' => 'Tucupita',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '10', 'nombre' => 'Acosta',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '10', 'nombre' => 'Bolívar',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '10', 'nombre' => 'Buchivacoa',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '10', 'nombre' => 'Cacique Manaure',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '10', 'nombre' => 'Carirubana',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '10', 'nombre' => 'Colina',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '10', 'nombre' => 'Dabajuro',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '10', 'nombre' => 'Democracia',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '10', 'nombre' => 'Falcón',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '10', 'nombre' => 'Federación',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '10', 'nombre' => 'Jacura',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '10', 'nombre' => 'José Laurencio Silva',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '10', 'nombre' => 'Los Taques',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '10', 'nombre' => 'Mauroa',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '10', 'nombre' => 'Miranda',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '10', 'nombre' => 'Monseñor Iturriza',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '10', 'nombre' => 'Palmasola',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '10', 'nombre' => 'Petit',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '10', 'nombre' => 'Píritu',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '10', 'nombre' => 'San Francisco',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '10', 'nombre' => 'Sucre',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '10', 'nombre' => 'Tocópero',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '10', 'nombre' => 'Unión',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '10', 'nombre' => 'Urumaco',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '10', 'nombre' => 'Zamora',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '11', 'nombre' => 'Camaguán',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '11', 'nombre' => 'Chaguaramas',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '11', 'nombre' => 'El Socorro',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '11', 'nombre' => 'José Félix Ribas',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '11', 'nombre' => 'José Tadeo Monagas',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '11', 'nombre' => 'Juan Germán Roscio',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '11', 'nombre' => 'Julián Mellado',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '11', 'nombre' => 'Las Mercedes',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '11', 'nombre' => 'Leonardo Infante',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '11', 'nombre' => 'Pedro Zaraza',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '11', 'nombre' => 'Ortíz',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '11', 'nombre' => 'San Gerónimo de Guayabal',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '11', 'nombre' => 'San José de Guaribe',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '11', 'nombre' => 'Santa María de Ipire',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '11', 'nombre' => 'Sebastián Francisco de Miranda',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '12', 'nombre' => 'Andrés Eloy Blanco',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '12', 'nombre' => 'Crespo',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '12', 'nombre' => 'Iribarren',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '12', 'nombre' => 'Jiménez',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '12', 'nombre' => 'Morán',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '12', 'nombre' => 'Palavecino',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '12', 'nombre' => 'Simón Planas',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '12', 'nombre' => 'Torres',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '12', 'nombre' => 'Urdaneta',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '13', 'nombre' => 'Alberto Adriani',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '13', 'nombre' => 'Andrés Bello',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '13', 'nombre' => 'Antonio Pinto Salinas',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '13', 'nombre' => 'Aricagua',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '13', 'nombre' => 'Arzobispo Chacón',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '13', 'nombre' => 'Campo Elías',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '13', 'nombre' => 'Caracciolo Parra Olmedo',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '13', 'nombre' => 'Cardenal Quintero',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '13', 'nombre' => 'Guaraque',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '13', 'nombre' => 'Julio César Salas',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '13', 'nombre' => 'Justo Briceño',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '13', 'nombre' => 'Libertador',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '13', 'nombre' => 'Miranda',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '13', 'nombre' => 'Obispo Ramos de Lora',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '13', 'nombre' => 'Padre Noguera',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '13', 'nombre' => 'Pueblo Llano',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '13', 'nombre' => 'Rangel',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '13', 'nombre' => 'Rivas Dávila',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '13', 'nombre' => 'Santos Marquina',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '13', 'nombre' => 'Sucre',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '13', 'nombre' => 'Tovar',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '13', 'nombre' => 'Tulio Febres Cordero',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '13', 'nombre' => 'Zea',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '14', 'nombre' => 'Acevedo',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '14', 'nombre' => 'Andrés Bello',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '14', 'nombre' => 'Baruta',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '14', 'nombre' => 'Brión',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '14', 'nombre' => 'Buroz',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '14', 'nombre' => 'Carrizal',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '14', 'nombre' => 'Chacao',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '14', 'nombre' => 'Cristóbal Rojas',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '14', 'nombre' => 'El Hatillo',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '14', 'nombre' => 'Guaicaipuro',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '14', 'nombre' => 'Independencia',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '14', 'nombre' => 'Lander',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '14', 'nombre' => 'Los Salias',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '14', 'nombre' => 'Páez',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '14', 'nombre' => 'Paz Castillo',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '14', 'nombre' => 'Pedro Gual',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '14', 'nombre' => 'Plaza',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '14', 'nombre' => 'Simón Bolívar',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '14', 'nombre' => 'Sucre',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '14', 'nombre' => 'Urdaneta',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '14', 'nombre' => 'Zamora',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '15', 'nombre' => 'Acosta',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '15', 'nombre' => 'Aguasay',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '15', 'nombre' => 'Bolívar',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '15', 'nombre' => 'Caripe',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '15', 'nombre' => 'Cedeño',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '15', 'nombre' => 'Ezequiel Zamora',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '15', 'nombre' => 'Libertador',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '15', 'nombre' => 'Maturín',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '15', 'nombre' => 'Piar',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '15', 'nombre' => 'Punceres',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '15', 'nombre' => 'Santa Bárbara',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '15', 'nombre' => 'Sotillo',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '15', 'nombre' => 'Uracoa',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '16', 'nombre' => 'Antolín del Campo',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '16', 'nombre' => 'Arismendi',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '16', 'nombre' => 'García',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '16', 'nombre' => 'Gómez',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '16', 'nombre' => 'Maneiro',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '16', 'nombre' => 'Marcano',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '16', 'nombre' => 'Mariño',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '16', 'nombre' => 'Península de Macanao',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '16', 'nombre' => 'Tubores',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '16', 'nombre' => 'Villalba',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '16', 'nombre' => 'Díaz',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '17', 'nombre' => 'Agua Blanca',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '17', 'nombre' => 'Araure',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '17', 'nombre' => 'Esteller',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '17', 'nombre' => 'Guanare',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '17', 'nombre' => 'Guanarito',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '17', 'nombre' => 'Monseñor José Vicente de Unda',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '17', 'nombre' => 'Ospino',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '17', 'nombre' => 'Páez',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '17', 'nombre' => 'Papelón',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '17', 'nombre' => 'San Genaro de Boconoíto',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '17', 'nombre' => 'San Rafael de Onoto',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '17', 'nombre' => 'Santa Rosalía',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '17', 'nombre' => 'Sucre',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '17', 'nombre' => 'Turén',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '18', 'nombre' => 'Andrés Eloy Blanco',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '18', 'nombre' => 'Andrés Mata',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '18', 'nombre' => 'Arismendi',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '18', 'nombre' => 'Benítez',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '18', 'nombre' => 'Bermúdez',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '18', 'nombre' => 'Bolívar',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '18', 'nombre' => 'Cajigal',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '18', 'nombre' => 'Cruz Salmerón Acosta',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '18', 'nombre' => 'Libertador',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '18', 'nombre' => 'Mariño',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '18', 'nombre' => 'Mejía',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '18', 'nombre' => 'Montes',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '18', 'nombre' => 'Ribero',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '18', 'nombre' => 'Sucre',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '18', 'nombre' => 'Valdéz',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '19', 'nombre' => 'Andrés Bello',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '19', 'nombre' => 'Antonio Rómulo Costa',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '19', 'nombre' => 'Ayacucho',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '19', 'nombre' => 'Bolívar',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '19', 'nombre' => 'Cárdenas',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '19', 'nombre' => 'Córdoba',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '19', 'nombre' => 'Fernández Feo',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '19', 'nombre' => 'Francisco de Miranda',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '19', 'nombre' => 'García de Hevia',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '19', 'nombre' => 'Guásimos',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '19', 'nombre' => 'Independencia',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '19', 'nombre' => 'Jáuregui',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '19', 'nombre' => 'José María Vargas',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '19', 'nombre' => 'Junín',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '19', 'nombre' => 'Libertad',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '19', 'nombre' => 'Libertador',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '19', 'nombre' => 'Lobatera',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '19', 'nombre' => 'Michelena',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '19', 'nombre' => 'Panamericano',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '19', 'nombre' => 'Pedro María Ureña',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '19', 'nombre' => 'Rafael Urdaneta',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '19', 'nombre' => 'Samuel Darío Maldonado',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '19', 'nombre' => 'San Cristóbal',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '19', 'nombre' => 'Seboruco',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '19', 'nombre' => 'Simón Rodríguez',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '19', 'nombre' => 'Sucre',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '19', 'nombre' => 'Torbes',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '19', 'nombre' => 'Uribante',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '19', 'nombre' => 'San Judas Tadeo',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '20', 'nombre' => 'Andrés Bello',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '20', 'nombre' => 'Boconó',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '20', 'nombre' => 'Bolívar',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '20', 'nombre' => 'Candelaria',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '20', 'nombre' => 'Carache',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '20', 'nombre' => 'Escuque',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '20', 'nombre' => 'José Felipe Márquez Cañizalez',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '20', 'nombre' => 'Juan Vicente Campos Elías',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '20', 'nombre' => 'La Ceiba',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '20', 'nombre' => 'Miranda',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '20', 'nombre' => 'Monte Carmelo',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '20', 'nombre' => 'Motatán',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '20', 'nombre' => 'Pampán',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '20', 'nombre' => 'Pampanito',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '20', 'nombre' => 'Rafael Rangel',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '20', 'nombre' => 'San Rafael de Carvajal',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '20', 'nombre' => 'Sucre',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '20', 'nombre' => 'Trujillo',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '20', 'nombre' => 'Urdaneta',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '20', 'nombre' => 'Valera',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '21', 'nombre' => 'Vargas',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '22', 'nombre' => 'Arístides Bastidas',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '22', 'nombre' => 'Bolívar',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '22', 'nombre' => 'Bruzual',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '22', 'nombre' => 'Cocorote',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '22', 'nombre' => 'Independencia',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '22', 'nombre' => 'José Antonio Páez',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '22', 'nombre' => 'La Trinidad',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '22', 'nombre' => 'Manuel Monge',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '22', 'nombre' => 'Nirgua',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '22', 'nombre' => 'Peña',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '22', 'nombre' => 'San Felipe',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '22', 'nombre' => 'Sucre',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '22', 'nombre' => 'Urachiche',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '22', 'nombre' => 'José Joaquín Veroes',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '23', 'nombre' => 'Almirante Padilla',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '23', 'nombre' => 'Baralt',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '23', 'nombre' => 'Cabimas',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '23', 'nombre' => 'Catatumbo',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '23', 'nombre' => 'Colón',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '23', 'nombre' => 'Francisco Javier Pulgar',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '23', 'nombre' => 'Páez',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '23', 'nombre' => 'Jesús Enrique Losada',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '23', 'nombre' => 'Jesús María Semprún',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '23', 'nombre' => 'La Cañada de Urdaneta',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '23', 'nombre' => 'Lagunillas',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '23', 'nombre' => 'Machiques de Perijá',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '23', 'nombre' => 'Mara',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '23', 'nombre' => 'Maracaibo',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '23', 'nombre' => 'Miranda',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '23', 'nombre' => 'Rosario de Perijá',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '23', 'nombre' => 'San Francisco',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '23', 'nombre' => 'Santa Rita',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '23', 'nombre' => 'Simón Bolívar',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '23', 'nombre' => 'Sucre',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '23', 'nombre' => 'Valmore Rodríguez',]);
        DB::table('municipio')->insert([ 'id_entidad'=> '24', 'nombre' => 'Libertador',]);
        


    }
}
